spring.application.name=demo

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 database configuration
spring.datasource.url=jdbc:h2:file:./data/testdb
# spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

# JWT settings
myjwttoken.app.jwtSecret=SecretKeyForMyJWTLogic3566235672725697901126559673860123852657010209566290767
myjwttoken.app.jwtExpirationMs=86400000


# logging.level.org.springframework.security=DEBUG